package proyectoorga;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JFormattedTextField;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gusta
 */
public class GUI extends javax.swing.JFrame {

   Estacionamiento estacionamiento = new Estacionamiento();
   private JFormattedTextField formatter;
    
    
    public GUI() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.net.URL iconURL = getClass().getResource("flagp.png");
        // iconURL is null when not found
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage()); 
        this.setTitle("Estacionamiento Don Joao");   
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        agregar_vehiculo = new javax.swing.JButton();
        buscar_vehiculo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ScrollCarros = new javax.swing.JScrollPane();
        ListaCarros = new java.awt.List();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ModeloCarro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MarcaCarro = new javax.swing.JLabel();
        MensualidadCarro = new javax.swing.JLabel();
        ColorCarro = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PlacaCarro = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");
        
        
            
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido al Estacionamiento Don Joao");

        agregar_vehiculo.setText("Agregar vehículo");
        agregar_vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_vehiculoActionPerformed(evt);
            }
        });

        buscar_vehiculo.setText("Buscar vehículo");
        buscar_vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_vehiculoActionPerformed(evt);
            }
        });

        

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(agregar_vehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    
                                        .addComponent(buscar_vehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 142,
                                                Short.MAX_VALUE))
                                .addGap(37, 37, 37)));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_vehiculo)
                    .addComponent(buscar_vehiculo)))
        );

        ListaCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaCarrosActionPerformed(evt);
            }
        });
        ScrollCarros.setViewportView(ListaCarros);

        jButton1.setText("Buscar seleccionado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ScrollCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(ScrollCarros, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );

        jLabel3.setText("Modelo:");

        jLabel4.setText("Marca:");

        jLabel5.setText("Color:");

        jLabel6.setText("Mensualidad:");

        jLabel8.setText("Placa:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(MarcaCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(9, 9, 9))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColorCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel3)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MensualidadCarro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(PlacaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ModeloCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(MarcaCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MensualidadCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(ColorCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlacaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    private void agregar_vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_vehiculoActionPerformed
        // TODO add your handling code here:
        
       
        String placa = JOptionPane.showInputDialog(this, "Ingrese la placa del carro", "Agregar Carro", JOptionPane.QUESTION_MESSAGE);
  
         while ("".equals(placa) || placa.length() != 7){
            JOptionPane.showMessageDialog(this, "La placa del carro no es valida", "Advertencia", JOptionPane.WARNING_MESSAGE);
            placa = JOptionPane.showInputDialog(this, "Ingrese la placa del carro", "Agregar Carro", JOptionPane.QUESTION_MESSAGE);
        }
         
        String marca = JOptionPane.showInputDialog(this, "Ingrese la marca del carro", "Agregar Carro", JOptionPane.QUESTION_MESSAGE);
        
         while ("".equals(marca) || marca.length() > 20){
            JOptionPane.showMessageDialog(this, "La marca no es valida", "Advertencia", JOptionPane.WARNING_MESSAGE);
            marca = JOptionPane.showInputDialog(this, "Ingrese la marca del carro", "Agregar Carro", JOptionPane.QUESTION_MESSAGE);
        }
         
        String modelo = JOptionPane.showInputDialog(this, "Ingrese el modelo del carro", "Agregar Carro", JOptionPane.QUESTION_MESSAGE);
        
         while ("".equals(modelo) || modelo.length() > 20){
            JOptionPane.showMessageDialog(this, "El modelo no es valido", "Advertencia", JOptionPane.WARNING_MESSAGE);
            modelo = JOptionPane.showInputDialog(this, "Ingrese el modelo del carro", "Agregar Carro", JOptionPane.QUESTION_MESSAGE);
        }
         
        String color = JOptionPane.showInputDialog(this, "Ingrese el color del carro", "Agregar Carro", JOptionPane.QUESTION_MESSAGE);
        
         while ("".equals(color) || color.length() > 10){
            JOptionPane.showMessageDialog(this, "El color no es valido", "Advertencia", JOptionPane.WARNING_MESSAGE);
            color = JOptionPane.showInputDialog(this, "Ingrese el color del carro", "Agregar Carro", JOptionPane.QUESTION_MESSAGE);
        }
         
        String mensualidadTemp = JOptionPane.showInputDialog(this, "Ingrese la mensualidad del carro", "Agregar Carro", JOptionPane.QUESTION_MESSAGE);
        
        while ("".equals(mensualidadTemp) || mensualidadTemp.length() > 3){
            JOptionPane.showMessageDialog(this, "La mesualidad no es valida", "Advertencia", JOptionPane.WARNING_MESSAGE);
            mensualidadTemp = JOptionPane.showInputDialog(this, "Ingrese la mensualidad del carro", "Agregar Carro", JOptionPane.QUESTION_MESSAGE);
        }
        
        int mensualidad = 0;
        
        try
    {
      // the String to int conversion happens here
      mensualidad = Integer.parseInt(mensualidadTemp);;

    }
    catch (NumberFormatException nfe)
    {
      JOptionPane.showMessageDialog(this, "La mesualidad ingresada no es valida", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
       

        //Si seleccionó el botón cancelar
        if (placa == null || marca == null || modelo == null || color == null || mensualidadTemp == null || mensualidad == 0){
            
        }
        else{
        
        Boolean agregado = estacionamiento.AgregarCarro(placa, marca, modelo, color, mensualidad);
        
        if(agregado == true){
        ListaCarros.add(placa);
         JOptionPane.showMessageDialog(this, "El carro ha sido agregado exitosamente", "Advertencia", JOptionPane.WARNING_MESSAGE);
         
          for(int x = 0; x < estacionamiento.estacionamiento.length; x++){
            for(int y = 0; y < estacionamiento.estacionamiento[x].length; y++){
                System.out.print(estacionamiento.estacionamiento[x][y]);
            }
            System.out.println("");
        }
        }
        else{
        JOptionPane.showMessageDialog(this, "El carro no se ha podido agregar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        }
        
        
        
        
    }//GEN-LAST:event_agregar_vehiculoActionPerformed

    private void ListaCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaCarrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaCarrosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String placa = ListaCarros.getSelectedItem();
        
        int key = estacionamiento.Hash(placa);
        
        Carros carro = estacionamiento.BuscarCarro(key, placa);
        
        ModeloCarro.setText(carro.getModelo());
        MarcaCarro.setText(carro.getMarca());
        ColorCarro.setText(carro.getColor());
        MensualidadCarro.setText(Integer.toString(carro.getMensualidad()));
        PlacaCarro.setText(carro.getPlaca());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscar_vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_vehiculoActionPerformed
     String[] decision1 = {"Buscar por Placa", "Buscar por modelo"};
        
        String decisionMenu1 = (String) JOptionPane.showInputDialog(null, "Seleccione el tipo de búsqueda", "Busqueda de vehículos", JOptionPane.QUESTION_MESSAGE, null, decision1, decision1[0]);

        if(decisionMenu1 == "Buscar por Placa"){
        String placa = JOptionPane.showInputDialog(this, "Ingrese la placa del vehículo a buscar", "Buscar vehículo", JOptionPane.QUESTION_MESSAGE);
         while ("".equals(placa) || placa.length() != 7){
            JOptionPane.showMessageDialog(this, "La placa del vehículo no es valida", "Advertencia", JOptionPane.WARNING_MESSAGE);
            placa = JOptionPane.showInputDialog(this, "Ingrese la placa del vehículo a buscar", "Buscar vehículo", JOptionPane.QUESTION_MESSAGE);
           
        } int key = estacionamiento.Hash(placa);
        Carros carro = estacionamiento.BuscarCarro(key, placa);
        if(carro!=null){
        ModeloCarro.setText(carro.getModelo());
        MarcaCarro.setText(carro.getMarca());
        ColorCarro.setText(carro.getColor());
        MensualidadCarro.setText(Integer.toString(carro.getMensualidad()));
        PlacaCarro.setText(carro.getPlaca());}
        else{JOptionPane.showMessageDialog(this, "El vehículo no se encuentra en la base de datos", "Advertencia", JOptionPane.WARNING_MESSAGE);}}
    
        
        else if(decisionMenu1 == "Buscar por modelo"){JOptionPane.showMessageDialog(null, "Busqueda por modelo");}}
            //GEN-LAST:event_buscar_vehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ColorCarro;
    private java.awt.List ListaCarros;
    private javax.swing.JLabel MarcaCarro;
    private javax.swing.JLabel MensualidadCarro;
    private javax.swing.JLabel ModeloCarro;
    private javax.swing.JLabel PlacaCarro;
    private javax.swing.JScrollPane ScrollCarros;
    private javax.swing.JButton agregar_vehiculo;
    private javax.swing.JButton buscar_vehiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
